# Generated by Django 2.2 on 2022-03-20 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name': '诗路类别', 'verbose_name_plural': '诗路类别'},
        ),
        migrations.AlterModelOptions(
            name='newschannel',
            options={'verbose_name': '诗路频道', 'verbose_name_plural': '诗路频道'},
        ),
        migrations.AddField(
            model_name='article',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='newsapp.NewsChannel', verbose_name='从属诗路'),
            preserve_default=False,
        ),
    ]
